Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'bin/**/*'
    - 'app/channels/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'


