Documentation:
  Enabled: false
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'bin/**/*'
    - 'app/channels/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'


